# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _mc
else:
    import _mc

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)



def mc_read(handle, buffer, count):
    return _mc.mc_read(handle, buffer, count)
class edit_buffer_t(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    curs1 = property(_mc.edit_buffer_t_curs1_get, _mc.edit_buffer_t_curs1_set)
    curs2 = property(_mc.edit_buffer_t_curs2_get, _mc.edit_buffer_t_curs2_set)
    b1 = property(_mc.edit_buffer_t_b1_get, _mc.edit_buffer_t_b1_set)
    b2 = property(_mc.edit_buffer_t_b2_get, _mc.edit_buffer_t_b2_set)
    size = property(_mc.edit_buffer_t_size_get, _mc.edit_buffer_t_size_set)
    lines = property(_mc.edit_buffer_t_lines_get, _mc.edit_buffer_t_lines_set)
    curs_line = property(_mc.edit_buffer_t_curs_line_get, _mc.edit_buffer_t_curs_line_set)

    def __init__(self):
        _mc.edit_buffer_t_swiginit(self, _mc.new_edit_buffer_t())
    __swig_destroy__ = _mc.delete_edit_buffer_t

# Register edit_buffer_t in _mc:
_mc.edit_buffer_t_swigregister(edit_buffer_t)

class edit_buffer_read_file_status_msg_t(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    status_msg = property(_mc.edit_buffer_read_file_status_msg_t_status_msg_get, _mc.edit_buffer_read_file_status_msg_t_status_msg_set)
    first = property(_mc.edit_buffer_read_file_status_msg_t_first_get, _mc.edit_buffer_read_file_status_msg_t_first_set)
    buf = property(_mc.edit_buffer_read_file_status_msg_t_buf_get, _mc.edit_buffer_read_file_status_msg_t_buf_set)
    loaded = property(_mc.edit_buffer_read_file_status_msg_t_loaded_get, _mc.edit_buffer_read_file_status_msg_t_loaded_set)

    def __init__(self):
        _mc.edit_buffer_read_file_status_msg_t_swiginit(self, _mc.new_edit_buffer_read_file_status_msg_t())
    __swig_destroy__ = _mc.delete_edit_buffer_read_file_status_msg_t

# Register edit_buffer_read_file_status_msg_t in _mc:
_mc.edit_buffer_read_file_status_msg_t_swigregister(edit_buffer_read_file_status_msg_t)


def edit_buffer_init(buf, size):
    return _mc.edit_buffer_init(buf, size)

def edit_buffer_clean(buf):
    return _mc.edit_buffer_clean(buf)

def edit_buffer_get_byte(buf, byte_index):
    return _mc.edit_buffer_get_byte(buf, byte_index)

def edit_buffer_count_lines(buf, first, last):
    return _mc.edit_buffer_count_lines(buf, first, last)

def edit_buffer_get_bol(buf, current):
    return _mc.edit_buffer_get_bol(buf, current)

def edit_buffer_get_eol(buf, current):
    return _mc.edit_buffer_get_eol(buf, current)

def edit_buffer_get_word_from_pos(buf, start_pos, start, cut):
    return _mc.edit_buffer_get_word_from_pos(buf, start_pos, start, cut)

def edit_buffer_insert(buf, c):
    return _mc.edit_buffer_insert(buf, c)

def edit_buffer_insert_ahead(buf, c):
    return _mc.edit_buffer_insert_ahead(buf, c)

def edit_buffer_delete(buf):
    return _mc.edit_buffer_delete(buf)

def edit_buffer_backspace(buf):
    return _mc.edit_buffer_backspace(buf)

def edit_buffer_get_forward_offset(buf, current, lines, upto):
    return _mc.edit_buffer_get_forward_offset(buf, current, lines, upto)

def edit_buffer_get_backward_offset(buf, current, lines):
    return _mc.edit_buffer_get_backward_offset(buf, current, lines)

def edit_buffer_read_file(buf, fd, size, sm, aborted):
    return _mc.edit_buffer_read_file(buf, fd, size, sm, aborted)

def edit_buffer_write_file(buf, fd):
    return _mc.edit_buffer_write_file(buf, fd)

def edit_buffer_calc_percent(buf, offset):
    return _mc.edit_buffer_calc_percent(buf, offset)

def edit_buffer_get_current_byte(buf):
    return _mc.edit_buffer_get_current_byte(buf)

def edit_buffer_get_previous_byte(buf):
    return _mc.edit_buffer_get_previous_byte(buf)

def edit_buffer_get_current_bol(buf):
    return _mc.edit_buffer_get_current_bol(buf)

def edit_buffer_get_current_eol(buf):
    return _mc.edit_buffer_get_current_eol(buf)


